[profile.default]
src = "src"
out = "out"
libs = ["lib"]
show_progress = true # Whether to show test execution progress.

# include remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@chimera/=lib/chimera/src/",
]

[fuzz]
runs = 1000
max_test_rejects = 999999999 # The maximum number of combined inputs that may be rejected before the test as a whole aborts. “Global” filters apply to the whole test case. If the test case is rejected, the whole thing is regenerated.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
